{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Phonenet APIs",
    "description" : "- Tích hợp nghe gọi ở front end:<space> [Phonenet SDK](https://github.com/gadgetvn/phonenet-sdk)\n- Để kết nối với các API được mô tả dưới đây:<space> Lấy token bằng cách đăng nhập vào tài khoản Callio đã được cung cấp rồi vào menu Cài đặt / Token. Truyền token vào header mỗi khi gửi request. Lưu ý: token của tài khoản có quyền nào thì bị giới hạn quyền đó\n",
    "termsOfService" : "http://swagger.io/terms/",
    "contact" : {
      "email" : "trangbn@gadget.com.vn"
    },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://clientapi.phonenet.io",
    "description" : "Phonenet API"
  } ],
  "security" : [ {
    "api_key" : [ "token" ]
  } ],
  "tags" : [ {
    "name" : "user",
    "description" : "Lấy danh sách, thêm, sửa, người dùng"
  }, {
    "name" : "customer",
    "description" : "Lấy danh sách, thêm, sửa, xóa khách hàng"
  }, {
    "name" : "contact",
    "description" : "Lấy danh sách, thêm, sửa, xóa liên hệ"
  }, {
    "name" : "opportunity",
    "description" : "These APIs support to create, get and update information of opportunity"
  } ],
  "paths" : {
    "/user" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "Lấy danh sách người dùng",
        "parameters" : [ {
          "name" : "page",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        }, {
          "name" : "pageSize",
          "in" : "query",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        }, {
          "name" : "status",
          "in" : "query",
          "description" : "Nhận các giá trị\n- 0:<space> đang hoạt động\n- 1:<space> dừng hoạt động\n",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "integer"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Lấy danh sách người dùng thành công",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        }
      },
      "post" : {
        "tags" : [ "user" ],
        "summary" : "Thêm mới người dùng",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/body"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Thêm mới người dùng thành công",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                },
                "examples" : {
                  "user1" : {
                    "$ref" : "#/components/examples/User1"
                  },
                  "user2" : {
                    "$ref" : "#/components/examples/User2"
                  }
                }
              }
            }
          },
          "422" : {
            "description" : "Lỗi validate",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errors"
                },
                "example" : [ {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "email",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Email không đúng",
                  "param" : "email",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "password",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Phải dài từ 7 đến 25 ký tự",
                  "param" : "password",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Phải là số nguyên",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "5 hoặc 6 số, không bắt đầu bằng 0",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "extPassword",
                  "location" : "body"
                }, {
                  "msg" : "Thông tin bắt buộc",
                  "param" : "name",
                  "location" : "body"
                } ]
              }
            }
          },
          "403" : {
            "description" : "Không có quyền thực hiện hành động",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_403"
                },
                "example" : {
                  "message" : "Bạn không có quyền thực hiện hành động này"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}" : {
      "get" : {
        "tags" : [ "user" ],
        "summary" : "Lấy chi tiết thông tin người dùng theo _id",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "_id của user",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Lấy thông tin chi tiết người dùng thành công",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                },
                "examples" : {
                  "user1" : {
                    "$ref" : "#/components/examples/User1"
                  },
                  "user2" : {
                    "$ref" : "#/components/examples/User2"
                  }
                }
              }
            }
          },
          "404" : {
            "description" : "Không tìm thấy dữ liệu",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_403"
                },
                "example" : {
                  "message" : "Không tìm thấy dữ liệu"
                }
              }
            }
          }
        }
      },
      "put" : {
        "tags" : [ "user" ],
        "summary" : "Cập nhật thông tin người dùng",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "_id của người dùng",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/body_1"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "Cập nhật thành công",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/User"
                },
                "examples" : {
                  "user2" : {
                    "$ref" : "#/components/examples/User2"
                  }
                }
              }
            }
          },
          "404" : {
            "description" : "Không tìm thấy dữ liệu",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_403"
                },
                "example" : {
                  "message" : "Không tìm thấy dữ liệu"
                }
              }
            }
          },
          "403" : {
            "description" : "Không có quyền thực hiện hành động",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_403"
                },
                "example" : {
                  "message" : "Bạn không có quyền thực hiện hành động này"
                }
              }
            }
          },
          "422" : {
            "description" : "Lỗi validate",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/errors"
                },
                "example" : [ {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "email",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Email không đúng",
                  "param" : "email",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "password",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Phải dài từ 7 đến 25 ký tự",
                  "param" : "password",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Phải là số nguyên",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "5 hoặc 6 số, không bắt đầu bằng 0",
                  "param" : "ext",
                  "location" : "body"
                }, {
                  "value" : "",
                  "msg" : "Thông tin bắt buộc",
                  "param" : "extPassword",
                  "location" : "body"
                }, {
                  "msg" : "Thông tin bắt buộc",
                  "param" : "name",
                  "location" : "body"
                } ]
              }
            }
          }
        }
      }
    },
    "/opportunity" : {
      "get" : {
        "tags" : [ "opportunity" ],
        "summary" : "Get opportunities",
        "operationId" : "getOpportunity",
        "parameters" : [ {
          "name" : "page",
          "in" : "query",
          "description" : "The beginning position of list",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pageSize",
          "in" : "query",
          "description" : "Number record per page",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "keyword",
          "in" : "query",
          "description" : "The search keyword",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "group",
          "in" : "query",
          "description" : "The group which has opportunity",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "customer",
          "in" : "query",
          "description" : "The customer name",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "user",
          "in" : "query",
          "description" : "The person in charge for opportunity",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "from",
          "in" : "query",
          "description" : "Create time from",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "number"
          }
        }, {
          "name" : "to",
          "in" : "query",
          "description" : "Create time to",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "number"
          }
        }, {
          "name" : "status",
          "in" : "query",
          "description" : "Status of opportunity:\n  * `new` - new \n  * `won` - won \n  * `lost` - lost \n  * other custom value\n",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "time",
          "in" : "query",
          "description" : "Time at creation or updating:\n  * `createTime`- create time \n  * `updateTime`- update time\n",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "createTime", "updateTime" ]
          }
        }, {
          "name" : "sort",
          "in" : "query",
          "description" : "Sort order:\n * `createTimeDESC` - New to old\n * `createTimeASC` - Old to new\n * `updateTimeDESC` - Recently update\n * `updateTimeASC` - Not recently update\n",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "enum" : [ "createTimeDESC", "createTimeASC", "updateTimeDESC", "updateTimeASC" ]
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_1"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid username/password supplied"
          }
        }
      },
      "post" : {
        "tags" : [ "opportunity" ],
        "summary" : "Create new opportunity",
        "operationId" : "createOpportunity",
        "requestBody" : {
          "description" : "Optional description in *Markdown*",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/body_2"
              },
              "example" : {
                "customer" : "60a547dc6e38c20161664fb0",
                "confidence" : 50,
                "contact" : {
                  "_id" : "60a547dc6e38c20161664fb1",
                  "gender" : "unknown",
                  "createTime" : 1621444572211,
                  "customFields" : [ ],
                  "customer" : "60a547dc6e38c20161664fb0",
                  "client" : "5e587b29356b577b2d0a279d",
                  "name" : "bob",
                  "phone" : 9.88868888E8,
                  "email" : "abcs@gmail.com",
                  "facebook" : "testfacesbook",
                  "address" : "awesome address",
                  "title" : "boss",
                  "__v" : 0
                },
                "users" : [ "609972fe12a7a63e4cdce333" ],
                "user" : "5efc5b11c441961ffe743f09",
                "status" : "new",
                "estimatedCloseTime" : 1621962000000,
                "amount" : 2000000,
                "name" : "rqrqwr"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "201" : {
            "description" : "Created"
          }
        }
      }
    },
    "/opportunity/{id}/status" : {
      "put" : {
        "tags" : [ "opportunity" ],
        "summary" : "Update status of opportunity",
        "operationId" : "update status of opportunity",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of opportunity",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Optional description in *Markdown*",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/body_3"
              },
              "example" : {
                "status" : "new"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "headers" : {
              "X-Rate-Limit" : {
                "description" : "calls per hour allowed by the user",
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "integer",
                  "format" : "int32"
                }
              },
              "X-Expires-After" : {
                "description" : "date in UTC when token expires",
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "format" : "date-time"
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "string"
                }
              },
              "application/xml" : {
                "schema" : {
                  "type" : "string"
                }
              }
            }
          },
          "400" : {
            "description" : "Invalid username/password supplied"
          }
        }
      }
    },
    "/opportunity/{id}" : {
      "get" : {
        "tags" : [ "opportunity" ],
        "summary" : "Get the specific opportunity by id",
        "operationId" : "getOpportunityById",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of opportunity",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_2"
                },
                "example" : {
                  "gender" : "unknown",
                  "_id" : "60a5434c0cd4e415537da6d8",
                  "createTime" : 1621443404152,
                  "customFields" : [ ],
                  "customer" : "60a5434c0cd4e415537da6d7",
                  "client" : "5e587b29356b577b2d0a279d",
                  "name" : "contactname",
                  "phone" : 9.88888886E8,
                  "email" : "comany2@gadget.com.vn",
                  "facebook" : "noface",
                  "address" : "awesomeaddress ",
                  "title" : "jobtitle1",
                  "__v" : 0
                }
              }
            }
          },
          "404" : {
            "description" : "Not found"
          }
        }
      },
      "put" : {
        "tags" : [ "opportunity" ],
        "summary" : "Update opportunity",
        "operationId" : "updateOpportunity",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of opportunity",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "requestBody" : {
          "description" : "Optional description in *Markdown*",
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/body_4"
              },
              "example" : {
                "users" : [ "609972fe12a7a63e4cdce333" ],
                "estimatedCloseTime" : 1622048204177,
                "wonTime" : 0,
                "lostTime" : 0,
                "cancelTime" : 0,
                "notifyTime" : 0,
                "_id" : "60a5434c0cd4e415537da6d9",
                "createTime" : 1621443404153,
                "updateTime" : 1621443404153,
                "customer" : "60a5434c0cd4e415537da6d7",
                "contact" : "60a5434c0cd4e415537da6d8",
                "user" : "5efc5b11c441961ffe743f09",
                "name" : "comapny02",
                "status" : "new",
                "confidence" : 50,
                "amount" : 0,
                "id" : "60a5434c0cd4e415537da6d9"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "successful operation"
          }
        }
      }
    },
    "/contact" : {
      "get" : {
        "tags" : [ "contact" ],
        "summary" : "get contacts of customer",
        "operationId" : "getContacts",
        "parameters" : [ {
          "name" : "page",
          "in" : "query",
          "description" : "The beginning position of list",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "pageSize",
          "in" : "query",
          "description" : "Number record per page",
          "required" : true,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_3"
                },
                "example" : {
                  "docs" : [ {
                    "gender" : "unknown",
                    "_id" : "60a547dc6e38c20161664fb1",
                    "createTime" : 1621444572211,
                    "customFields" : [ ],
                    "customer" : {
                      "users" : [ ],
                      "_id" : "60a547dc6e38c20161664fb0",
                      "createTime" : 1621444572210,
                      "updateTime" : 1621470286379,
                      "name" : "company 3",
                      "client" : "5e587b29356b577b2d0a279d",
                      "__v" : 1,
                      "mainContact" : "60a547dc6e38c20161664fb1",
                      "user" : "5efc5b11c441961ffe743f09",
                      "customFields" : [ ],
                      "id" : "60a547dc6e38c20161664fb0"
                    },
                    "client" : "5e587b29356b577b2d0a279d",
                    "name" : "bob",
                    "phone" : 9.88868888E8,
                    "email" : "abcs@gmail.com",
                    "facebook" : "testfacesbook",
                    "address" : "awesome address",
                    "title" : "boss",
                    "__v" : 0
                  } ],
                  "totalDocs" : 1,
                  "limit" : 5,
                  "totalPages" : 1,
                  "page" : 1,
                  "pagingCounter" : 1,
                  "hasPrevPage" : false,
                  "hasNextPage" : false
                }
              }
            }
          }
        }
      }
    },
    "/contact/{id}" : {
      "get" : {
        "tags" : [ "contact" ],
        "summary" : "Get contact by id",
        "operationId" : "getContactById",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of contact",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Response body",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_2"
                },
                "example" : {
                  "gender" : "unknown",
                  "_id" : "60a547dc6e38c20161664fb1",
                  "createTime" : 1621444572211,
                  "customFields" : [ ],
                  "customer" : "60a547dc6e38c20161664fb0",
                  "client" : "5e587b29356b577b2d0a279d",
                  "name" : "bob",
                  "phone" : 9.88868888E8,
                  "email" : "abcs@gmail.com",
                  "facebook" : "testfacesbook",
                  "address" : "awesome address",
                  "title" : "boss",
                  "__v" : 0
                }
              }
            }
          },
          "404" : {
            "description" : "Not found"
          }
        }
      },
      "put" : {
        "tags" : [ "contact" ],
        "summary" : "Update contact of customer",
        "operationId" : "updateContact",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of contact",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "response body",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_4"
                },
                "example" : {
                  "gender" : "unknown",
                  "_id" : "60a5434c0cd4e415537da6d8",
                  "createTime" : 1621443404152,
                  "customer" : "60a5434c0cd4e415537da6d7",
                  "client" : "5e587b29356b577b2d0a279d",
                  "name" : "contactname",
                  "phone" : 9.88888886E8,
                  "email" : "comany2@gadget.com.vn",
                  "facebook" : "noface",
                  "address" : "awesomeaddress ",
                  "title" : "jobtitle1",
                  "id" : "60a5434c0cd4e415537da6d8"
                }
              }
            }
          }
        }
      },
      "delete" : {
        "tags" : [ "contact" ],
        "summary" : "Delete contact of customer",
        "operationId" : "deleteContact",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "The id of contact",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "400" : {
            "description" : "Invalid ID supplied"
          },
          "404" : {
            "description" : "Contact not found"
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "Customer" : {
        "required" : [ "contactName", "customerName" ],
        "type" : "object",
        "properties" : {
          "autoCreateOpportunity" : {
            "type" : "boolean"
          },
          "user" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "customerName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "contactName" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "users" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        },
        "example" : {
          "autoCreateOpportunity" : true,
          "user" : "5efc5b11c441961ffe743f09",
          "phone" : 9.88888888E8,
          "customerName" : "company 1",
          "email" : "abc@gmail.com",
          "title" : "boss",
          "address" : "awesome address",
          "contactName" : "bob",
          "facebook" : "testfacebook",
          "users" : [ "609972fe12a7a63e4cdce333" ]
        }
      },
      "Opportunity" : {
        "type" : "object",
        "properties" : {
          "client" : {
            "type" : "number"
          },
          "customer" : {
            "type" : "number"
          },
          "contact" : {
            "type" : "number"
          },
          "user" : {
            "type" : "number"
          },
          "users" : {
            "type" : "array",
            "items" : {
              "type" : "number"
            }
          },
          "name" : {
            "type" : "string"
          },
          "amount" : {
            "type" : "number"
          },
          "status" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "number"
          },
          "updateTime" : {
            "type" : "number"
          },
          "confidence" : {
            "type" : "number"
          },
          "estimatedCloseTime" : {
            "type" : "number"
          },
          "wonTime" : {
            "type" : "number"
          },
          "lostTime" : {
            "type" : "number"
          },
          "cancelTime" : {
            "type" : "number"
          },
          "notifyTime" : {
            "type" : "number"
          }
        }
      },
      "Contact" : {
        "type" : "object",
        "properties" : {
          "client" : {
            "type" : "number"
          },
          "customer" : {
            "type" : "number"
          },
          "name" : {
            "type" : "string"
          },
          "company" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "desc" : {
            "type" : "string"
          },
          "gender" : {
            "type" : "string",
            "default" : "unknown",
            "enum" : [ "unknown", "male", "female" ]
          },
          "dob" : {
            "type" : "number"
          },
          "phone" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "number"
          },
          "updateTime" : {
            "type" : "number"
          },
          "customFields" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/CustomerFields"
            }
          }
        }
      },
      "CustomerFields" : {
        "type" : "object",
        "properties" : {
          "key" : {
            "$ref" : "#/components/schemas/CustomerFields_key"
          },
          "val" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/CustomerFields_key"
            }
          }
        }
      },
      "User" : {
        "type" : "object",
        "properties" : {
          "active" : {
            "type" : "boolean",
            "description" : "Tình trạng user có đang được hoạt động hay không"
          },
          "createTime" : {
            "type" : "integer",
            "description" : "Thời gian tạo. Timestamp milliseconds"
          },
          "email" : {
            "type" : "string"
          },
          "ext" : {
            "type" : "string",
            "description" : "Số máy nhánh của user"
          },
          "extPassword" : {
            "type" : "string",
            "description" : "Mật khẩu nhánh (dùng để gọi điện) của user (mật khẩu này không phải mật khẩu đăng nhập)"
          },
          "group" : {
            "type" : "string",
            "description" : "ObjectId nhóm của user"
          },
          "lastOnlineTime" : {
            "type" : "integer",
            "description" : "Thời gian hoạt động cuối của user"
          },
          "name" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "role" : {
            "type" : "string",
            "description" : "Mã quyền của user"
          },
          "_id" : {
            "type" : "string",
            "description" : "_id của user (ObjectId)"
          }
        }
      },
      "errors" : {
        "type" : "array",
        "items" : {
          "$ref" : "#/components/schemas/errors_inner"
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "docs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/User"
            }
          },
          "totalDocs" : {
            "type" : "integer"
          },
          "limit" : {
            "type" : "integer"
          },
          "totalPages" : {
            "type" : "integer"
          },
          "page" : {
            "type" : "integer"
          },
          "pagingCounter" : {
            "type" : "integer"
          },
          "hasPrevPage" : {
            "type" : "boolean"
          },
          "hasNextPage" : {
            "type" : "boolean"
          },
          "prevPage" : {
            "type" : "integer"
          },
          "nextPage" : {
            "type" : "integer"
          }
        }
      },
      "body" : {
        "required" : [ "email", "ext", "extPassword", "name", "password", "role" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "Tên dài không quá 50 ký tự"
          },
          "email" : {
            "type" : "string",
            "description" : "Email cần phải là duy nhất trên toàn hệ thống"
          },
          "password" : {
            "type" : "string",
            "description" : "Mật khẩu dài từ 7 đến 25 ký tự"
          },
          "phone" : {
            "type" : "string",
            "description" : "Số điện thoại chỉ chứa ký tự số, dài từ 7 đến 15 ký tự"
          },
          "desc" : {
            "type" : "string",
            "description" : "Mô tả user. Dài không quá 500 ký tự"
          },
          "ext" : {
            "type" : "string",
            "description" : "Số nhánh của user. Có thể là 1 giá trị trong khoảng từ 10000 đến 999999 và phải là duy nhất"
          },
          "extPassword" : {
            "type" : "string",
            "description" : "Mật khẩu nhánh dài từ 7 đến 25 ký tự, chỉ chứa các ký tự chữ và số và -"
          },
          "group" : {
            "type" : "string",
            "description" : "_id của nhóm user"
          },
          "role" : {
            "type" : "string",
            "description" : "Mã quyền của user. Có 3 quyền mặc định là owner (chủ tài khoản), supervisor (trưởng nhóm) và agent (nhân viên). Các quyền tùy biến khác có thể được tạo ra ở menu Cài đặt / quyền"
          },
          "active" : {
            "type" : "boolean",
            "description" : "Cho phép tài khoản được hoạt động hay không. Nếu không truyền giá trị thì đồng nghĩa với active = false"
          }
        }
      },
      "inline_response_403" : {
        "type" : "object",
        "properties" : {
          "message" : {
            "type" : "string"
          }
        }
      },
      "body_1" : {
        "required" : [ "email", "ext", "extPassword", "name", "role" ],
        "type" : "object",
        "properties" : {
          "name" : {
            "type" : "string",
            "description" : "Tên dài không quá 50 ký tự"
          },
          "email" : {
            "type" : "string",
            "description" : "Email cần phải là duy nhất trên toàn hệ thống"
          },
          "phone" : {
            "type" : "string",
            "description" : "Số điện thoại chỉ chứa ký tự số, dài từ 7 đến 15 ký tự"
          },
          "desc" : {
            "type" : "string",
            "description" : "Mô tả user. Dài không quá 500 ký tự"
          },
          "ext" : {
            "type" : "string",
            "description" : "Số nhánh của user. Có thể là 1 giá trị trong khoảng từ 10000 đến 999999 và phải là duy nhất"
          },
          "extPassword" : {
            "type" : "string",
            "description" : "Mật khẩu nhánh dài từ 7 đến 25 ký tự, chỉ chứa các ký tự chữ và số và -"
          },
          "group" : {
            "type" : "string",
            "description" : "_id của nhóm user"
          },
          "role" : {
            "type" : "string",
            "description" : "Mã quyền của user. Có 3 quyền mặc định là owner (chủ tài khoản), supervisor (trưởng nhóm) và agent (nhân viên). Các quyền tùy biến khác có thể được tạo ra ở menu Cài đặt / quyền"
          },
          "active" : {
            "type" : "boolean",
            "description" : "Cho phép tài khoản được hoạt động hay không. Nếu không truyền giá trị thì đồng nghĩa với active = false"
          }
        }
      },
      "inline_response_200_1" : {
        "type" : "object",
        "properties" : {
          "docs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/inline_response_200_1_docs"
            }
          },
          "totalDocs" : {
            "type" : "integer"
          },
          "limit" : {
            "type" : "integer"
          },
          "totalPages" : {
            "type" : "integer"
          },
          "page" : {
            "type" : "integer"
          },
          "pagingCounter" : {
            "type" : "integer"
          },
          "hasPrevPage" : {
            "type" : "boolean"
          },
          "hasNextPage" : {
            "type" : "boolean"
          },
          "prevPage" : {
            "type" : "integer"
          },
          "nextPage" : {
            "type" : "integer"
          },
          "report" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/inline_response_200_1_report"
            }
          }
        },
        "example" : {
          "docs" : [ {
            "_id" : "60a547dc6e38c20161664fb2",
            "users" : [ ],
            "estimatedCloseTime" : 1622049372253,
            "wonTime" : 0,
            "lostTime" : 0,
            "cancelTime" : 0,
            "notifyTime" : 0,
            "createTime" : 1621444572213,
            "updateTime" : 1621444572213,
            "client" : "5e587b29356b577b2d0a279d",
            "customer" : {
              "_id" : "60a547dc6e38c20161664fb0",
              "users" : [ ],
              "createTime" : 1621444572210,
              "updateTime" : 1621444572215,
              "name" : "company 3",
              "client" : "5e587b29356b577b2d0a279d",
              "__v" : 0,
              "mainContact" : "60a547dc6e38c20161664fb1",
              "user" : "5efc5b11c441961ffe743f09"
            },
            "contact" : {
              "_id" : "60a547dc6e38c20161664fb1",
              "gender" : "unknown",
              "createTime" : 1621444572211,
              "customFields" : [ ],
              "customer" : "60a547dc6e38c20161664fb0",
              "client" : "5e587b29356b577b2d0a279d",
              "name" : "bob",
              "phone" : 9.88868888E8,
              "email" : "abcs@gmail.com",
              "facebook" : "testfacesbook",
              "address" : "awesome address",
              "title" : "boss",
              "__v" : 0
            },
            "user" : {
              "_id" : "5efc5b11c441961ffe743f09",
              "active" : true,
              "role" : "owner",
              "email" : "trangbn@gadget.com.vn",
              "ext" : "191981",
              "createTime" : 1593596689374,
              "client" : "5e587b29356b577b2d0a279d",
              "name" : "TrangBN",
              "language" : "en",
              "password" : "$2a$10$zeAgFKQJpOhiGyT2jvju8.l9bgQH198EKCCW2o214vnskHDoNbwY2",
              "extPassword" : "caigido",
              "__v" : 0,
              "socketId" : "/client#x-2RuYgsddQ0TsMTBFP0",
              "phone" : 9.6981658E8,
              "lastOnlineTime" : 0,
              "updateTime" : 0
            },
            "name" : "company 3",
            "status" : "new",
            "confidence" : 50,
            "amount" : 0,
            "__v" : 0,
            "id" : "60a547dc6e38c20161664fb2"
          } ],
          "totalDocs" : 246,
          "limit" : 1,
          "totalPages" : 246,
          "page" : 1,
          "pagingCounter" : 1,
          "hasPrevPage" : false,
          "hasNextPage" : true,
          "nextPage" : 2,
          "report" : [ {
            "_id" : "thang-05",
            "total" : 0
          }, {
            "_id" : "dang-cho",
            "total" : 1000000
          }, {
            "_id" : "new",
            "total" : 17842594
          }, {
            "_id" : "canceled",
            "total" : 123456
          }, {
            "_id" : "tam-11",
            "total" : 10000
          }, {
            "_id" : "won",
            "total" : 1600100
          } ]
        }
      },
      "opportunity_contact" : {
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string"
          },
          "gender" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "customFields" : {
            "type" : "array",
            "items" : { }
          },
          "customer" : {
            "type" : "string"
          },
          "client" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          }
        }
      },
      "body_2" : {
        "required" : [ "amount", "contact", "estimatedCloseTime", "name" ],
        "type" : "object",
        "properties" : {
          "customer" : {
            "type" : "string"
          },
          "confidence" : {
            "type" : "integer"
          },
          "contact" : {
            "$ref" : "#/components/schemas/opportunity_contact"
          },
          "users" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "user" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "estimatedCloseTime" : {
            "type" : "integer"
          },
          "amount" : {
            "type" : "integer"
          },
          "price" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          }
        }
      },
      "body_3" : {
        "required" : [ "status" ],
        "type" : "object",
        "properties" : {
          "status" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_2" : {
        "type" : "object",
        "properties" : {
          "gender" : {
            "type" : "string"
          },
          "_id" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "customFields" : {
            "type" : "array",
            "items" : { }
          },
          "customer" : {
            "type" : "string"
          },
          "client" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          }
        }
      },
      "body_4" : {
        "required" : [ "contact", "estimatedCloseTime", "name" ],
        "type" : "object",
        "properties" : {
          "users" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "estimatedCloseTime" : {
            "type" : "integer"
          },
          "wonTime" : {
            "type" : "integer"
          },
          "lostTime" : {
            "type" : "integer"
          },
          "cancelTime" : {
            "type" : "integer"
          },
          "notifyTime" : {
            "type" : "integer"
          },
          "_id" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "updateTime" : {
            "type" : "integer"
          },
          "customer" : {
            "type" : "string"
          },
          "contact" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "confidence" : {
            "type" : "integer"
          },
          "amount" : {
            "type" : "integer"
          },
          "id" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_3" : {
        "type" : "object",
        "properties" : {
          "docs" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/inline_response_200_3_docs"
            }
          },
          "totalDocs" : {
            "type" : "integer"
          },
          "limit" : {
            "type" : "integer"
          },
          "totalPages" : {
            "type" : "integer"
          },
          "page" : {
            "type" : "integer"
          },
          "pagingCounter" : {
            "type" : "integer"
          },
          "hasPrevPage" : {
            "type" : "boolean"
          },
          "hasNextPage" : {
            "type" : "boolean"
          },
          "prevPage" : {
            "type" : "integer"
          },
          "nextPage" : {
            "type" : "integer"
          }
        }
      },
      "inline_response_200_4" : {
        "type" : "object",
        "properties" : {
          "gender" : {
            "type" : "string"
          },
          "_id" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "customer" : {
            "type" : "string"
          },
          "client" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          },
          "id" : {
            "type" : "string"
          }
        }
      },
      "CustomerFields_key" : {
        "type" : "object",
        "properties" : {
          "type" : {
            "type" : "string"
          },
          "index" : {
            "type" : "boolean",
            "default" : true
          }
        }
      },
      "errors_inner" : {
        "type" : "object",
        "properties" : {
          "param" : {
            "type" : "string",
            "description" : "Trường thông tin"
          },
          "value" : {
            "type" : "string",
            "description" : "Giá trị đã truyền"
          },
          "msg" : {
            "type" : "string",
            "description" : "Mô tả lỗi"
          },
          "location" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_1_customer" : {
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string"
          },
          "users" : {
            "type" : "array",
            "items" : { }
          },
          "createTime" : {
            "type" : "integer"
          },
          "updateTime" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "client" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          },
          "mainContact" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_1_user" : {
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string"
          },
          "active" : {
            "type" : "boolean"
          },
          "role" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "group" : {
            "type" : "string"
          },
          "ext" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "client" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "language" : {
            "type" : "string"
          },
          "password" : {
            "type" : "string"
          },
          "extPassword" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          },
          "socketId" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "lastOnlineTime" : {
            "type" : "integer"
          },
          "updateTime" : {
            "type" : "integer"
          }
        }
      },
      "inline_response_200_1_docs" : {
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string"
          },
          "users" : {
            "type" : "array",
            "items" : { }
          },
          "estimatedCloseTime" : {
            "type" : "integer"
          },
          "wonTime" : {
            "type" : "integer"
          },
          "lostTime" : {
            "type" : "integer"
          },
          "cancelTime" : {
            "type" : "integer"
          },
          "notifyTime" : {
            "type" : "integer"
          },
          "createTime" : {
            "type" : "integer"
          },
          "updateTime" : {
            "type" : "integer"
          },
          "client" : {
            "type" : "string"
          },
          "customer" : {
            "$ref" : "#/components/schemas/inline_response_200_1_customer"
          },
          "contact" : {
            "$ref" : "#/components/schemas/opportunity_contact"
          },
          "user" : {
            "$ref" : "#/components/schemas/inline_response_200_1_user"
          },
          "name" : {
            "type" : "string"
          },
          "status" : {
            "type" : "string"
          },
          "confidence" : {
            "type" : "integer"
          },
          "amount" : {
            "type" : "integer"
          },
          "__v" : {
            "type" : "integer"
          },
          "id" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_1_report" : {
        "type" : "object",
        "properties" : {
          "_id" : {
            "type" : "string"
          },
          "total" : {
            "type" : "integer"
          }
        }
      },
      "inline_response_200_3_customer" : {
        "type" : "object",
        "properties" : {
          "users" : {
            "type" : "array",
            "items" : { }
          },
          "_id" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "updateTime" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "client" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          },
          "mainContact" : {
            "type" : "string"
          },
          "user" : {
            "type" : "string"
          },
          "customFields" : {
            "type" : "array",
            "items" : { }
          },
          "id" : {
            "type" : "string"
          }
        }
      },
      "inline_response_200_3_docs" : {
        "type" : "object",
        "properties" : {
          "gender" : {
            "type" : "string"
          },
          "_id" : {
            "type" : "string"
          },
          "createTime" : {
            "type" : "integer"
          },
          "customFields" : {
            "type" : "array",
            "items" : { }
          },
          "customer" : {
            "$ref" : "#/components/schemas/inline_response_200_3_customer"
          },
          "client" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "phone" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "facebook" : {
            "type" : "string"
          },
          "address" : {
            "type" : "string"
          },
          "title" : {
            "type" : "string"
          },
          "__v" : {
            "type" : "integer"
          }
        }
      }
    },
    "responses" : {
      "404" : {
        "description" : "Không tìm thấy dữ liệu",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/inline_response_403"
            },
            "example" : {
              "message" : "Không tìm thấy dữ liệu"
            }
          }
        }
      },
      "403" : {
        "description" : "Không có quyền thực hiện hành động",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/inline_response_403"
            },
            "example" : {
              "message" : "Bạn không có quyền thực hiện hành động này"
            }
          }
        }
      },
      "422" : {
        "description" : "Lỗi validate",
        "content" : {
          "application/json" : {
            "schema" : {
              "$ref" : "#/components/schemas/errors"
            }
          }
        }
      }
    },
    "examples" : {
      "User1" : {
        "value" : {
          "active" : true,
          "role" : "owner",
          "updateTime" : 0,
          "lastOnlineTime" : 0,
          "_id" : "5efc5b11c441961ffe743f09",
          "email" : "trangbn@gadget.com.vn",
          "ext" : "191981",
          "createTime" : 1593596689374,
          "client" : "5e587b29356b577b2d0a279d",
          "name" : "TrangBN",
          "language" : "vi",
          "password" : "$2a$10$zeAgFKQJpOhiGyT2jvju8.l9bgQH198EKCCW2o214vnskHDoNbwY2",
          "extPassword" : "caigido",
          "__v" : 0,
          "socketId" : "/client#pkIJAsKssJZJC9jNAAAD",
          "phone" : 9.6981658E8,
          "id" : "5efc5b11c441961ffe743f09"
        }
      },
      "User2" : {
        "value" : {
          "active" : true,
          "role" : "clone-admin",
          "updateTime" : 0,
          "lastOnlineTime" : 0,
          "_id" : "5fea9fe7f1801c51183cf2c4",
          "name" : "Tèo",
          "email" : "teo@gmail.com",
          "password" : "$2a$10$t4NW9U9YCd0Q/DJMyoC9pO1zHL4le0CZzxUTBtjlax3pPGRoNkLKy",
          "phone" : "1234567",
          "desc" : "tèo",
          "moh" : "5f6c4106b5ee655fa1c13165",
          "ext" : "212345",
          "extPassword" : "212345cccc",
          "createTime" : 1609211879088,
          "client" : "5e587b29356b577b2d0a279d",
          "language" : "vi",
          "__v" : 0,
          "group" : "5e587d12976eb31ef43d10d0",
          "socketId" : "/client#LEL1O5ogWBj1rK4ZA5m0",
          "id" : "5fea9fe7f1801c51183cf2c4"
        }
      }
    },
    "requestBodies" : {
      "UserArray" : {
        "description" : "List of user object",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/components/schemas/Customer"
              }
            }
          }
        },
        "required" : true
      }
    },
    "securitySchemes" : {
      "api_key" : {
        "type" : "apiKey",
        "name" : "token",
        "in" : "header"
      }
    }
  }
}